export interface PermissionDefinition {
  id: string; // e.g. 'org.company.view'
  module: string; // e.g. 'org'
  action: string; // e.g. 'view'
  description: string;
}

/**
 * The 11 Approved Action Primitives:
 * view, create, edit, delete, export, approve, reject, post, cancel, reverse, print
 */
export const APPROVED_ACTION_PRIMITIVES = [
  'view',
  'create',
  'edit',
  'delete',
  'export',
  'approve',
  'reject',
  'post',
  'cancel',
  'reverse',
  'print',
] as const;

export type ActionPrimitive = (typeof APPROVED_ACTION_PRIMITIVES)[number];

/**
 * Standard Seed Permission Catalogue for Foundation Modules (org, auth, audit, system)
 * Covers all 11 action primitives across foundational enterprise domains.
 */
export const STANDARD_PERMISSIONS: PermissionDefinition[] = [
  // Org Module - Company
  { id: 'org.company.view', module: 'org', action: 'view', description: 'View company profile, structure, and parameters' },
  { id: 'org.company.create', module: 'org', action: 'create', description: 'Provision new operating companies' },
  { id: 'org.company.edit', module: 'org', action: 'edit', description: 'Update company legal and operating settings' },
  { id: 'org.company.delete', module: 'org', action: 'delete', description: 'Deactivate or remove unposted company entities' },
  { id: 'org.company.export', module: 'org', action: 'export', description: 'Export company directory and structured reports' },

  // Org Module - Branch
  { id: 'org.branch.view', module: 'org', action: 'view', description: 'View branches within authorized companies' },
  { id: 'org.branch.create', module: 'org', action: 'create', description: 'Provision new operating branch locations' },
  { id: 'org.branch.edit', module: 'org', action: 'edit', description: 'Update branch settings and address parameters' },
  { id: 'org.branch.delete', module: 'org', action: 'delete', description: 'Deactivate or delete unposted branch records' },
  { id: 'org.branch.export', module: 'org', action: 'export', description: 'Export branch location datasets' },

  // Org Module - Warehouse
  { id: 'org.warehouse.view', module: 'org', action: 'view', description: 'View warehouses and storage facilities' },
  { id: 'org.warehouse.create', module: 'org', action: 'create', description: 'Provision physical and virtual storage warehouses' },
  { id: 'org.warehouse.edit', module: 'org', action: 'edit', description: 'Update warehouse configurations and storage parameters' },
  { id: 'org.warehouse.delete', module: 'org', action: 'delete', description: 'Remove inactive or empty warehouse facilities' },
  { id: 'org.warehouse.post', module: 'org', action: 'post', description: 'Post inventory balance opening/reconciliation adjustments' },
  { id: 'org.warehouse.export', module: 'org', action: 'export', description: 'Export warehouse capacity and listing data' },

  // Auth Module - User
  { id: 'auth.user.view', module: 'auth', action: 'view', description: 'View user directory and assignment statuses' },
  { id: 'auth.user.create', module: 'auth', action: 'create', description: 'Provision new user identities' },
  { id: 'auth.user.edit', module: 'auth', action: 'edit', description: 'Update user profiles and active account status' },
  { id: 'auth.user.delete', module: 'auth', action: 'delete', description: 'Deactivate user accounts' },
  { id: 'auth.user.export', module: 'auth', action: 'export', description: 'Export user registry and identity logs' },

  // Auth Module - Role & RBAC
  { id: 'auth.role.view', module: 'auth', action: 'view', description: 'View roles, permissions, and company assignments' },
  { id: 'auth.role.create', module: 'auth', action: 'create', description: 'Create custom roles' },
  { id: 'auth.role.edit', module: 'auth', action: 'edit', description: 'Modify role permission bindings' },
  { id: 'auth.role.delete', module: 'auth', action: 'delete', description: 'Delete unassigned custom roles' },

  // Audit Module - Logs
  { id: 'audit.log.view', module: 'audit', action: 'view', description: 'Inspect immutable system audit trail events' },
  { id: 'audit.log.export', module: 'audit', action: 'export', description: 'Export structured audit trail logs for statutory compliance' },

  // System Module - Numbering Series & Approvals/Reversals Action Primitives
  { id: 'system.series.view', module: 'system', action: 'view', description: 'View numbering series configurations' },
  { id: 'system.series.edit', module: 'system', action: 'edit', description: 'Configure document numbering sequences' },
  { id: 'system.workflow.approve', module: 'system', action: 'approve', description: 'Approve pending workflow documents' },
  { id: 'system.workflow.reject', module: 'system', action: 'reject', description: 'Reject submitted workflow documents' },
  { id: 'system.document.cancel', module: 'system', action: 'cancel', description: 'Cancel unposted approved documents' },
  { id: 'system.document.reverse', module: 'system', action: 'reverse', description: 'Post compensating reversals on posted transactions' },
  { id: 'system.document.print', module: 'system', action: 'print', description: 'Generate official print and PDF outputs' },

  // Master Data Module - Items
  { id: 'master.item.view', module: 'master', action: 'view', description: 'View item and product catalog records' },
  { id: 'master.item.create', module: 'master', action: 'create', description: 'Create item master records and conversion ratios' },
  { id: 'master.item.edit', module: 'master', action: 'edit', description: 'Update item specifications, descriptions, and categories' },
  { id: 'master.item.delete', module: 'master', action: 'delete', description: 'Deactivate or soft-delete item records' },
  { id: 'master.item.export', module: 'master', action: 'export', description: 'Export item catalog data and price lists' },

  // Master Data Module - Business Partners
  { id: 'master.partner.view', module: 'master', action: 'view', description: 'View customer and supplier business partner records' },
  { id: 'master.partner.create', module: 'master', action: 'create', description: 'Create customer and supplier partner records' },
  { id: 'master.partner.edit', module: 'master', action: 'edit', description: 'Update business partner profiles, addresses, and contacts' },
  { id: 'master.partner.delete', module: 'master', action: 'delete', description: 'Deactivate or soft-delete business partner records' },
  { id: 'master.partner.export', module: 'master', action: 'export', description: 'Export business partner registries and directories' },

  // Master Data Module - Item Categories
  { id: 'master.category.view', module: 'master', action: 'view', description: 'View product and material category hierarchy' },
  { id: 'master.category.create', module: 'master', action: 'create', description: 'Create product taxonomy and material categories' },
  { id: 'master.category.edit', module: 'master', action: 'edit', description: 'Modify category attributes and hierarchy structures' },
  { id: 'master.category.delete', module: 'master', action: 'delete', description: 'Deactivate or remove unassigned categories' },

  // Master Data Module - Units of Measure (UOM)
  { id: 'master.uom.view', module: 'master', action: 'view', description: 'View units of measure master catalog' },
  { id: 'master.uom.create', module: 'master', action: 'create', description: 'Define new units of measure and symbols' },
  { id: 'master.uom.edit', module: 'master', action: 'edit', description: 'Modify unit of measure specifications and symbols' },
  { id: 'master.uom.delete', module: 'master', action: 'delete', description: 'Deactivate unreferenced units of measure' },

  // Purchasing Module - Purchase Orders
  { id: 'purchase.order.view', module: 'purchase', action: 'view', description: 'View purchase orders and line item schedules' },
  { id: 'purchase.order.create', module: 'purchase', action: 'create', description: 'Draft new purchase orders' },
  { id: 'purchase.order.edit', module: 'purchase', action: 'edit', description: 'Modify draft purchase orders' },
  { id: 'purchase.order.delete', module: 'purchase', action: 'delete', description: 'Remove unsubmitted purchase orders' },
  { id: 'purchase.order.approve', module: 'purchase', action: 'approve', description: 'Approve submitted purchase orders' },
  { id: 'purchase.order.reject', module: 'purchase', action: 'reject', description: 'Reject submitted purchase orders' },
  { id: 'purchase.order.cancel', module: 'purchase', action: 'cancel', description: 'Cancel approved or draft purchase orders' },
  { id: 'purchase.order.export', module: 'purchase', action: 'export', description: 'Export purchase order registers' },
  { id: 'purchase.order.print', module: 'purchase', action: 'print', description: 'Print official purchase order documents' },

  // Purchasing Module - Purchase Receipts / Material Receipt
  { id: 'purchase.receipt.view', module: 'purchase', action: 'view', description: 'View goods receipt notes and material inward logs' },
  { id: 'purchase.receipt.create', module: 'purchase', action: 'create', description: 'Create draft material inward receipts' },
  { id: 'purchase.receipt.edit', module: 'purchase', action: 'edit', description: 'Modify draft purchase receipts' },
  { id: 'purchase.receipt.delete', module: 'purchase', action: 'delete', description: 'Delete draft purchase receipts' },
  { id: 'purchase.receipt.approve', module: 'purchase', action: 'approve', description: 'Approve material inward receipts' },
  { id: 'purchase.receipt.reject', module: 'purchase', action: 'reject', description: 'Reject material inward receipts' },
  { id: 'purchase.receipt.post', module: 'purchase', action: 'post', description: 'Post material receipts to inventory ledger' },
  { id: 'purchase.receipt.cancel', module: 'purchase', action: 'cancel', description: 'Cancel unposted purchase receipts' },
  { id: 'purchase.receipt.reverse', module: 'purchase', action: 'reverse', description: 'Post reversing transaction to cancel posted receipt' },
  { id: 'purchase.receipt.export', module: 'purchase', action: 'export', description: 'Export material receipt registers' },
  { id: 'purchase.receipt.print', module: 'purchase', action: 'print', description: 'Print goods receipt note documents' },

  // Inventory Module - Batches & Lots
  { id: 'inventory.batch.view', module: 'inventory', action: 'view', description: 'View inventory lot and batch details' },
  { id: 'inventory.batch.create', module: 'inventory', action: 'create', description: 'Create new batch identifiers and cost layers' },
  { id: 'inventory.batch.edit', module: 'inventory', action: 'edit', description: 'Update batch metadata and expiry dates' },
  { id: 'inventory.batch.export', module: 'inventory', action: 'export', description: 'Export batch traceability registers' },

  // Inventory Module - Quality Control (QC)
  { id: 'inventory.qc.view', module: 'inventory', action: 'view', description: 'View QC inspection reports and lot results' },
  { id: 'inventory.qc.create', module: 'inventory', action: 'create', description: 'Create quality inspection records' },
  { id: 'inventory.qc.edit', module: 'inventory', action: 'edit', description: 'Update inspection sampling and pass/fail counts' },
  { id: 'inventory.qc.approve', module: 'inventory', action: 'approve', description: 'Approve quality inspection findings' },
  { id: 'inventory.qc.reject', module: 'inventory', action: 'reject', description: 'Reject quality inspection records' },
  { id: 'inventory.qc.post', module: 'inventory', action: 'post', description: 'Post QC release and restriction to stock ledger' },
  { id: 'inventory.qc.cancel', module: 'inventory', action: 'cancel', description: 'Cancel draft QC inspections' },
  { id: 'inventory.qc.export', module: 'inventory', action: 'export', description: 'Export QC inspection logs' },

  // Purchasing Module - Purchase Returns
  { id: 'purchase.return.view', module: 'purchase', action: 'view', description: 'View purchase returns and supplier debit notes' },
  { id: 'purchase.return.create', module: 'purchase', action: 'create', description: 'Draft purchase returns from QC failed inventory' },
  { id: 'purchase.return.edit', module: 'purchase', action: 'edit', description: 'Modify draft purchase returns' },
  { id: 'purchase.return.delete', module: 'purchase', action: 'delete', description: 'Delete draft purchase returns' },
  { id: 'purchase.return.approve', module: 'purchase', action: 'approve', description: 'Approve purchase returns' },
  { id: 'purchase.return.reject', module: 'purchase', action: 'reject', description: 'Reject purchase returns' },
  { id: 'purchase.return.post', module: 'purchase', action: 'post', description: 'Post purchase return stock deductions' },
  { id: 'purchase.return.cancel', module: 'purchase', action: 'cancel', description: 'Cancel unposted purchase returns' },
  { id: 'purchase.return.reverse', module: 'purchase', action: 'reverse', description: 'Reverse posted purchase returns' },
  { id: 'purchase.return.export', module: 'purchase', action: 'export', description: 'Export purchase return registers' },

  // Inventory Module - Stock Ledger & Balances
  { id: 'inventory.stock.view', module: 'inventory', action: 'view', description: 'View stock ledger movements and balance summaries' },
  { id: 'inventory.stock.post', module: 'inventory', action: 'post', description: 'Post stock balance reconciliation movements' },
  { id: 'inventory.stock.export', module: 'inventory', action: 'export', description: 'Export stock ledger and balance reports' },

  // Sales Module - Sales Orders
  { id: 'sales.order.view', module: 'sales', action: 'view', description: 'View sales orders, pricing, and line item schedules' },
  { id: 'sales.order.create', module: 'sales', action: 'create', description: 'Draft new sales orders with customers' },
  { id: 'sales.order.edit', module: 'sales', action: 'edit', description: 'Modify draft sales orders' },
  { id: 'sales.order.delete', module: 'sales', action: 'delete', description: 'Delete draft sales orders' },
  { id: 'sales.order.approve', module: 'sales', action: 'approve', description: 'Approve submitted sales orders' },
  { id: 'sales.order.reject', module: 'sales', action: 'reject', description: 'Reject submitted sales orders' },
  { id: 'sales.order.post', module: 'sales', action: 'post', description: 'Post and confirm sales orders for fulfillment' },
  { id: 'sales.order.cancel', module: 'sales', action: 'cancel', description: 'Cancel approved or draft sales orders' },
  { id: 'sales.order.export', module: 'sales', action: 'export', description: 'Export sales order registers' },
  { id: 'sales.order.print', module: 'sales', action: 'print', description: 'Print official sales order documents' },

  // Sales Module - Stock Reservations
  { id: 'sales.reservation.view', module: 'sales', action: 'view', description: 'View stock reservation allocations' },
  { id: 'sales.reservation.create', module: 'sales', action: 'create', description: 'Create stock reservations against approved sales orders' },
  { id: 'sales.reservation.release', module: 'sales', action: 'cancel', description: 'Release stock reservations back to available pool' },
  { id: 'sales.reservation.export', module: 'sales', action: 'export', description: 'Export stock reservation schedules' },

  // Sales Module - Deliveries / Goods Delivery Notes (GDN)
  { id: 'sales.delivery.view', module: 'sales', action: 'view', description: 'View delivery notes and shipping schedules' },
  { id: 'sales.delivery.create', module: 'sales', action: 'create', description: 'Draft goods delivery notes and batch allocations' },
  { id: 'sales.delivery.edit', module: 'sales', action: 'edit', description: 'Modify draft delivery notes' },
  { id: 'sales.delivery.delete', module: 'sales', action: 'delete', description: 'Delete draft delivery notes' },
  { id: 'sales.delivery.approve', module: 'sales', action: 'approve', description: 'Approve goods delivery notes' },
  { id: 'sales.delivery.reject', module: 'sales', action: 'reject', description: 'Reject goods delivery notes' },
  { id: 'sales.delivery.post', module: 'sales', action: 'post', description: 'Post sales deliveries to deduct physical stock from ledger' },
  { id: 'sales.delivery.cancel', module: 'sales', action: 'cancel', description: 'Cancel unposted goods delivery notes' },
  { id: 'sales.delivery.reverse', module: 'sales', action: 'reverse', description: 'Reverse posted delivery with compensating ledger movements' },
  { id: 'sales.delivery.export', module: 'sales', action: 'export', description: 'Export goods delivery note registers' },
  { id: 'sales.delivery.print', module: 'sales', action: 'print', description: 'Print delivery challans and packing slips' },

  // Sales Module - Invoicing & Accounts Receivable (AR)
  { id: 'sales.invoice.view', module: 'sales', action: 'view', description: 'View customer sales invoices and receivables' },
  { id: 'sales.invoice.create', module: 'sales', action: 'create', description: 'Draft customer sales invoices from orders or deliveries' },
  { id: 'sales.invoice.edit', module: 'sales', action: 'edit', description: 'Modify draft sales invoices' },
  { id: 'sales.invoice.delete', module: 'sales', action: 'delete', description: 'Delete draft sales invoices' },
  { id: 'sales.invoice.approve', module: 'sales', action: 'approve', description: 'Approve customer sales invoices' },
  { id: 'sales.invoice.reject', module: 'sales', action: 'reject', description: 'Reject customer sales invoices' },
  { id: 'sales.invoice.post', module: 'sales', action: 'post', description: 'Post sales invoices and establish customer receivables' },
  { id: 'sales.invoice.cancel', module: 'sales', action: 'cancel', description: 'Cancel unposted sales invoices' },
  { id: 'sales.invoice.reverse', module: 'sales', action: 'reverse', description: 'Reverse posted sales invoices and receivables' },
  { id: 'sales.invoice.export', module: 'sales', action: 'export', description: 'Export sales invoice registers' },
  { id: 'sales.invoice.print', module: 'sales', action: 'print', description: 'Print tax invoices and customer statements' },
];

export interface StandardRoleDefinition {
  code: string;
  name: string;
  description: string;
  isSystem: boolean;
  permissions: string[]; // List of permission keys or '*'
}

/**
 * The 5 Standard System Roles
 */
export const STANDARD_ROLES: StandardRoleDefinition[] = [
  {
    code: 'SUPERADMIN',
    name: 'Super Administrator',
    description: 'Platform-wide administrator with unrestricted system authority across all companies',
    isSystem: true,
    permissions: ['*'],
  },
  {
    code: 'COMPANY_ADMIN',
    name: 'Company Administrator',
    description: 'Full administrative management within the assigned company and its branches',
    isSystem: true,
    permissions: [
      'org.company.view',
      'org.company.edit',
      'org.company.export',
      'org.branch.view',
      'org.branch.create',
      'org.branch.edit',
      'org.branch.delete',
      'org.branch.export',
      'org.warehouse.view',
      'org.warehouse.create',
      'org.warehouse.edit',
      'org.warehouse.delete',
      'org.warehouse.post',
      'org.warehouse.export',
      'auth.user.view',
      'auth.user.create',
      'auth.user.edit',
      'auth.role.view',
      'auth.role.create',
      'auth.role.edit',
      'audit.log.view',
      'audit.log.export',
      'system.series.view',
      'system.series.edit',
      'system.workflow.approve',
      'system.workflow.reject',
      'system.document.cancel',
      'system.document.reverse',
      'system.document.print',
      'master.item.view',
      'master.item.create',
      'master.item.edit',
      'master.item.delete',
      'master.item.export',
      'master.partner.view',
      'master.partner.create',
      'master.partner.edit',
      'master.partner.delete',
      'master.partner.export',
      'master.category.view',
      'master.category.create',
      'master.category.edit',
      'master.category.delete',
      'master.uom.view',
      'master.uom.create',
      'master.uom.edit',
      'master.uom.delete',
      'purchase.order.view',
      'purchase.order.create',
      'purchase.order.edit',
      'purchase.order.delete',
      'purchase.order.approve',
      'purchase.order.reject',
      'purchase.order.cancel',
      'purchase.order.export',
      'purchase.order.print',
      'purchase.receipt.view',
      'purchase.receipt.create',
      'purchase.receipt.edit',
      'purchase.receipt.delete',
      'purchase.receipt.approve',
      'purchase.receipt.reject',
      'purchase.receipt.post',
      'purchase.receipt.cancel',
      'purchase.receipt.reverse',
      'purchase.receipt.export',
      'purchase.receipt.print',
      'inventory.batch.view',
      'inventory.batch.create',
      'inventory.batch.edit',
      'inventory.batch.export',
      'inventory.qc.view',
      'inventory.qc.create',
      'inventory.qc.edit',
      'inventory.qc.approve',
      'inventory.qc.reject',
      'inventory.qc.post',
      'inventory.qc.cancel',
      'inventory.qc.export',
      'purchase.return.view',
      'purchase.return.create',
      'purchase.return.edit',
      'purchase.return.delete',
      'purchase.return.approve',
      'purchase.return.reject',
      'purchase.return.post',
      'purchase.return.cancel',
      'purchase.return.reverse',
      'purchase.return.export',
      'inventory.stock.view',
      'inventory.stock.post',
      'inventory.stock.export',
      'sales.order.view',
      'sales.order.create',
      'sales.order.edit',
      'sales.order.delete',
      'sales.order.approve',
      'sales.order.reject',
      'sales.order.post',
      'sales.order.cancel',
      'sales.order.export',
      'sales.order.print',
      'sales.reservation.view',
      'sales.reservation.create',
      'sales.reservation.release',
      'sales.reservation.export',
      'sales.delivery.view',
      'sales.delivery.create',
      'sales.delivery.edit',
      'sales.delivery.delete',
      'sales.delivery.approve',
      'sales.delivery.reject',
      'sales.delivery.post',
      'sales.delivery.cancel',
      'sales.delivery.reverse',
      'sales.delivery.export',
      'sales.delivery.print',
    ],
  },
  {
    code: 'BRANCH_MANAGER',
    name: 'Branch Manager',
    description: 'Operational manager for assigned branch location and warehouses',
    isSystem: true,
    permissions: [
      'org.company.view',
      'org.branch.view',
      'org.warehouse.view',
      'org.warehouse.create',
      'org.warehouse.edit',
      'org.warehouse.post',
      'org.warehouse.export',
      'auth.user.view',
      'system.workflow.approve',
      'system.workflow.reject',
      'system.document.cancel',
      'system.document.print',
      'master.item.view',
      'master.partner.view',
      'master.category.view',
      'master.uom.view',
      'purchase.order.view',
      'purchase.order.create',
      'purchase.order.edit',
      'purchase.order.approve',
      'purchase.order.reject',
      'purchase.order.cancel',
      'purchase.receipt.view',
      'purchase.receipt.create',
      'purchase.receipt.edit',
      'purchase.receipt.approve',
      'purchase.receipt.post',
      'inventory.batch.view',
      'inventory.qc.view',
      'inventory.qc.approve',
      'inventory.qc.post',
      'purchase.return.view',
      'purchase.return.create',
      'purchase.return.approve',
      'purchase.return.post',
      'inventory.stock.view',
      'inventory.stock.export',
      'sales.order.view',
      'sales.order.create',
      'sales.order.edit',
      'sales.order.approve',
      'sales.order.reject',
      'sales.order.post',
      'sales.order.cancel',
      'sales.reservation.view',
      'sales.reservation.create',
      'sales.reservation.release',
      'sales.delivery.view',
      'sales.delivery.create',
      'sales.delivery.edit',
      'sales.delivery.approve',
      'sales.delivery.post',
      'sales.delivery.cancel',
      'sales.invoice.view',
      'sales.invoice.create',
      'sales.invoice.edit',
      'sales.invoice.approve',
      'sales.invoice.reject',
      'sales.invoice.post',
      'sales.invoice.cancel',
      'sales.invoice.reverse',
      'sales.invoice.export',
      'sales.invoice.print',
    ],
  },
  {
    code: 'WAREHOUSE_OPERATOR',
    name: 'Warehouse Operator',
    description: 'Operational floor personnel handling storage, receiving, packing, and posting',
    isSystem: true,
    permissions: [
      'org.warehouse.view',
      'org.warehouse.post',
      'system.document.print',
      'master.item.view',
      'master.uom.view',
      'master.category.view',
      'purchase.receipt.view',
      'purchase.receipt.create',
      'purchase.receipt.edit',
      'purchase.receipt.post',
      'inventory.batch.view',
      'inventory.batch.create',
      'inventory.qc.view',
      'inventory.qc.create',
      'purchase.return.view',
      'purchase.return.create',
      'inventory.stock.view',
      'sales.delivery.view',
      'sales.delivery.create',
      'sales.delivery.edit',
      'sales.delivery.post',
      'sales.reservation.view',
    ],
  },
  {
    code: 'AUDITOR_READONLY',
    name: 'Auditor (Read-Only)',
    description: 'Read-only inspection and export rights for compliance and financial audit',
    isSystem: true,
    permissions: [
      'org.company.view',
      'org.company.export',
      'org.branch.view',
      'org.branch.export',
      'org.warehouse.view',
      'org.warehouse.export',
      'auth.user.view',
      'auth.user.export',
      'auth.role.view',
      'audit.log.view',
      'audit.log.export',
      'system.series.view',
      'system.document.print',
      'master.item.view',
      'master.item.export',
      'master.partner.view',
      'master.partner.export',
      'master.category.view',
      'master.uom.view',
      'purchase.order.view',
      'purchase.order.export',
      'purchase.receipt.view',
      'purchase.receipt.export',
      'inventory.batch.view',
      'inventory.batch.export',
      'inventory.qc.view',
      'inventory.qc.export',
      'purchase.return.view',
      'purchase.return.export',
      'inventory.stock.view',
      'inventory.stock.export',
      'sales.order.view',
      'sales.order.export',
      'sales.reservation.view',
      'sales.reservation.export',
      'sales.delivery.view',
      'sales.delivery.export',
      'sales.invoice.view',
      'sales.invoice.export',
      'sales.invoice.print',
    ],
  },
];
